// AUTO-GENERATED by scripts/set-backend.mjs — do not edit by hand.
//
// The backend this checkout extension calls. Checkout UI extensions run in a
// sandboxed Web Worker (no `process`) and Shopify does not inline env vars at
// build, so the URL must be baked into source. The committed default points at
// PROD; `pnpm shopify:deploy:dev` rewrites it to the qa backend before deploy.
export const BASE_URL = 'https://shopify-qa.eboxsecure.com'
