#!/usr/bin/env node
// Rewrites the checkout extension's BASE_URL for the target environment.
//
// Checkout UI extensions can't read process.env at runtime (they run in a
// sandboxed Web Worker with no `process`) and Shopify does not inline env vars
// at build time, so the backend URL is baked into src/env.ts. Run this before
// `shopify app deploy` so the deployed bundle carries the URL for the app being
// deployed:
//
//   node scripts/set-backend.mjs dev    # eboxsecure-dev app  -> qa backend
//   node scripts/set-backend.mjs prod   # EboxSecure app      -> prod backend

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const BACKENDS = {
  dev: 'https://shopify-qa.eboxsecure.com',
  prod: 'https://shopify.eboxsecure.com',
}

const target = process.argv[2]
const url = BACKENDS[target]
if (!url) {
  console.error(
    `set-backend: expected "dev" or "prod", got ${JSON.stringify(target)}`,
  )
  process.exit(1)
}

// Keep this byte-identical to the committed env.ts when target === "prod" so a
// prod deploy leaves the working tree clean.
const render = backend => `// AUTO-GENERATED by scripts/set-backend.mjs — do not edit by hand.
//
// The backend this checkout extension calls. Checkout UI extensions run in a
// sandboxed Web Worker (no \`process\`) and Shopify does not inline env vars at
// build, so the URL must be baked into source. The committed default points at
// PROD; \`pnpm shopify:deploy:dev\` rewrites it to the qa backend before deploy.
export const BASE_URL = '${backend}'
`

const out = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'extensions',
  'ebox-location-picker',
  'src',
  'env.ts',
)
writeFileSync(out, render(url))
console.log(`set-backend: ${target} -> BASE_URL = ${url}`)
