import { ORDER_HANDLERS, ORDER_WEBHOOK_PROCESSORS } from './order.js'
import {
  FULFILLMENT_HANDLERS,
  FULFILLMENT_WEBHOOK_PROCESSORS,
} from './fulfillment.js'

import PRIVACY_HANDLERS from './privacy.js'

const WEBHOOK_PROCESSORS = {
  ...ORDER_WEBHOOK_PROCESSORS,
  ...FULFILLMENT_WEBHOOK_PROCESSORS,
}

const WEBHOOK_HANDLERS = {
  ...PRIVACY_HANDLERS,
  ...ORDER_HANDLERS,
  ...FULFILLMENT_HANDLERS,
}

export { WEBHOOK_PROCESSORS, WEBHOOK_HANDLERS }
