# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "93f19ebe1ec0cb32788dc8a11ef5035a"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "eboxsecure-dev"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
